### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by jake-g** [milkey-mouse/JSSCC#4]
the hosted gh-pages is broke, and when i host locally, same issue. the whole ui is froze, cant drag a file ect

**Comment by twilligon** [comment]
Yes, this project is dead, or at least shelved. Not only have I mostly lost interest in JSSCC, there are a few problems:

- For one, the performance of the pixel-for-pixel recreation of the GXSCC UI is not very good. (Which is mainly due to the immediate-mode canvas rendering, a choice that would only be made by someone used to programming games for old systems...)

- After getting this far into the project I realized how much more I liked programming in lower level languages anyway (although if I had to develop for the web, I'd choose TypeScript over JS again any day), making the JS version kind of moot for me.

I should probably archive the repository, but I might want to pick up this project in the future. Being open-source, anyone who wants to further this project can fork it and finish the synthesizer.

Another approach might be to try compiling the desktop version into WebAssembly with e.g. [Emscripten](https://kripken.github.io/emscripten-site/), but as I mentioned I have less experience developing for browsers than many.
